# docker-compose.yml
services:
  # The PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ats
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ats"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Spring Boot Backend Service
  app:
    build:
      context: ./backend 
    container_name: ats-software-pro-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce-network

  # === NEW: The React Frontend Service ===
  frontend:
    build:
      context: ./frontend 
    container_name: ats-software-pro-frontend
    ports:
      - "5173:80"
    depends_on:
      - app
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

# Define the volume for persistent database data
volumes:
  postgres-data:
